### ISSUE TITLE
Feature request: Support for logging torch.tensors as videos

### ISSUE THREAD

**Issue by fcakyon** [layerai/sdk#147]
## Summary

Support for logging torch.tensors as videos.

Looking at the documents, I see no support for video logging? https://docs.app.layer.ai/docs/sdk-library/layer-log

Being able to directly log a video tensor of shape NxTxCxHxW as a video/gif file would make things easier.

Reference API from tensorboard: https://pytorch.org/docs/stable/tensorboard.html#torch.utils.tensorboard.writer.SummaryWriter.add_video

**Comment by mecevit** [comment]
Implemented with:

https://github.com/layerai/sdk/pull/232


![Image](https://user-images.githubusercontent.com/63518291/184122364-fb31f869-a9e7-44d2-a981-a14e0089f6af.png)
