### ISSUE TITLE
Feature request: LayerLogger for Pytorch Lightning

### ISSUE THREAD

**Issue by fcakyon** [layerai/sdk#178]
[Pytorch Lightning](https://github.com/Lightning-AI/lightning) is the most accepted model training framework among Pytorch community.

Currently it includes logger wrappers for MLFlow, Neptune, Tensorboard, WANDB etc: https://pytorch-lightning.readthedocs.io/en/stable/common/loggers.html

Would be great if LayerLogger class could be added.

**Comment by mecevit** [comment]
Should be pretty straightforward to implement as we already have some callback loggers. Anything specific you want to see in the logs? @fcakyon

**Comment by fcakyon** [comment]
Being able to log hyperparams at the start, epoch-based metrics, predictions images/videos per epoch, confusion matrix images per epoch, and checkpoint files are the most essential functions for me.

**Comment by fcakyon** [comment]
This PR solves this issue I believe: https://github.com/layerai/sdk/pull/312 How to import the `LayerLogger` class?

**Comment by mecevit** [comment]
I'm working on a notebook, I'll link it here shortly @fcakyon

**Comment by mecevit** [comment]
@fcakyon Here you go:
```python
from pytorch_lightning import Trainer

from layer import PytorchLightningLogger
layer_logger = PytorchLightningLogger(project_name='MNIST', api_key='[YOUR_API_KEY]')

trainer = Trainer(
        logger=layer_logger,
        accelerator='gpu', devices=1)  
trainer.fit(model, training_loader, validation_loader)
```

Notebook:
https://colab.research.google.com/drive/1ygiC7R-mozacXq_tSCAj8wBbUE05xTpN?usp=sharing
