### ISSUE TITLE
[request]: get experiment url by python api

### ISSUE THREAD

**Issue by fcakyon** [layerai/sdk#314]
In Neptune we can get current experiment URL as:

```python
import neptune.new as Neptune

run = neptune.init()
run.get_url()
```

It would be great if we can do the same with Layer.

Currently Layer gives only project URL:

```python
import layer
from layer.config import DEFAULT_PATH, ConfigManager

layer_project = layer.init(PROJECT_NAME)
layer_config = ConfigManager(DEFAULT_PATH).load()
project_url = f'{layer_config.url}/{layer_project.account.name}/{layer_project.name}'
```

**Comment by volkangurel** [comment]
Would something like this work?
```python
import layer

layer_project = layer.init(PROJECT_NAME)
project_url = layer_project.url()
```

**Comment by fcakyon** [comment]
I need the current experiment URL rather than the project URL.

It should return something like this:

```python
'https://app.layer.ai/ACCOUNT_NAME/PROJECT_NAME/models/MODEL_NAME?v=1.3'
```

**Comment by adrien-layer** [comment]
Hi @fcakyon , this is great feedback thank you.

At the moment we log the different URLs when doing `layer.run([trainFunction])` like for example:
<img width="778" alt="Screenshot 2022-08-16 at 09 21 47" src="https://user-images.githubusercontent.com/86921811/184821466-508dbb16-b567-4a46-9eb2-b5dcf287aa40.png">

(So that is after having initialized the project workspace with `layer.init("ACCOUNT_NAME/PROJECT_NAME")`)

What would be the most useful for you between these possibilities:
a) `Run` instance has a `run.get("MODEL_NAME").get_url()`
b) `Run` instance has `run.get_urls()[0]` (we only have one entry since we did `layer.run([trainFunction])`)
b) A "better" `layer.init` experience with for example `layer.init("ACCOUNT_NAME/PROJECT_NAME/models/MODEL_NAME")` which would make the current workspace focus on a single model.

Maybe you even have a better idea, looking forward to hearing from you.

**Comment by fcakyon** [comment]
Thanks for the detailed explanation @adrien-layer. 

I don't use `layer.run`, my usage is like this: 

```python
import layer

def run_experiment(**kwargs):
    ...

layer.model(MODEL_NAME)(run_experiment)(**kwargs)
```

What I need is: inside the `run_experiment` function, I want to fetch current experiment URL as

```python
import layer

def run_experiment(**kwargs):
    current_experiment_url = layer.get_url()

layer.model(MODEL_NAME)(run_experiment)(**kwargs)
```

Is it possible with the current API?

**Comment by adrien-layer** [comment]
thank you for explaining further @fcakyon . I understand much better now.

in the context of your usage of `layer`, an experiment is what we currently call "model train" and has such URLs yes `'https://app.layer.ai/ACCOUNT_NAME/PROJECT_NAME/models/MODEL_NAME?v=1.3'`

can you show me a bigger example of how you use layer so i could use it in my work and tests please?

currently the API for what you ask is not there but we can totally add it. i just want to be able to reproduce a good use case for you

**Comment by fcakyon** [comment]
> in the context of your usage of `layer`, an experiment is what we currently call "model train" and has such URLs yes `'https://app.layer.ai/ACCOUNT_NAME/PROJECT_NAME/models/MODEL_NAME?v=1.3'`

Yes this is correct

**Comment by fcakyon** [comment]
> can you show me a bigger example of how you use layer so i could use it in my work and tests please?

I am using layer to perform training in my local and log results/models to layer with the example use case I posted above. What detail are you asking for?

**Comment by adrien-layer** [comment]
Thank you very much, I don't need more details actually. The API is not present yet but will be soon!

Out of curiosity to understand your use case better, why do you need to access the URL in there? is it for logging or other purposes? maybe we can help further after this

**Comment by adrien-layer** [comment]
Im working on a prototype for this new API to get the experiment URL. Here Im making it available via kwarg injection (`layer_` prefix to not risk overriding)

<img width="873" alt="Screenshot 2022-08-17 at 08 26 27" src="https://user-images.githubusercontent.com/86921811/185049684-365ea857-01a5-46a9-882c-b4dcd68ebb6d.png">
```python
def run_experiment(name, *, layer_model_train_url=""):
    print(f"Hello {name}, your experiment URL is {layer_model_train_url}")

layer.model("m1")(run_experiment)("bob")
```
is it a good way for you to get the URL?

we could pass a `layer_model_train` object instead and it would have `.url` and other useful things attached to it

**Comment by adrien-layer** [comment]
After some thoughts and internal discussions, we're going to propose something else where we would instead get this information from `context` 
will share something soon

**Comment by fcakyon** [comment]
> Out of curiosity to understand your use case better, why do you need to access the URL in there? is it for logging or other purposes? maybe we can help further after this

I need to log the experiment URL for some special reasons :)

**Comment by fcakyon** [comment]
> Im working on a prototype for this new API to get the experiment URL. Here Im making it available via kwarg injection (`layer_` prefix to not risk overriding)
> 
> <img alt="Screenshot 2022-08-17 at 08 26 27" width="873" src="https://user-images.githubusercontent.com/86921811/185049684-365ea857-01a5-46a9-882c-b4dcd68ebb6d.png">
> 
> ```python
> def run_experiment(name, *, layer_model_train_url=""):
>     print(f"Hello {name}, your experiment URL is {layer_model_train_url}")
> 
> layer.model("m1")(run_experiment)("bob")
> ```
> 
> is it a good way for you to get the URL?
> 
> we could pass a `layer_model_train` object instead and it would have `.url` and other useful things attached to it

Is there any way without injecting to input? It would be better if there was a way to get current experiment as object from `layer`module

**Comment by adrien-layer** [comment]
indeed yes, we agree context is better :) 

How about something like this? we can improve naming if not the best.
<img width="875" alt="Screenshot 2022-08-17 at 09 59 09" src="https://user-images.githubusercontent.com/86921811/185066395-3423d25b-1197-4b66-902e-b7939f15873f.png">

**Comment by fcakyon** [comment]
> we would provide a `layer.get_active_asset_url()` for example

that would be wonderful :100:

**Comment by adrien-layer** [comment]
Hello @fcakyon , sorry for keeping you waiting, here is a pull request with screenshots showing the usage of `layer.get_active_context()`
https://github.com/layerai/sdk/pull/353
<img width="815" alt="Screenshot 2022-08-24 at 11 01 48" src="https://user-images.githubusercontent.com/86921811/186389208-b0fc2a50-9abe-4b7a-bde2-b6c56f9353d6.png">

it is a bit different from what we discussed because we want to make more things available via active context.

does it look good to you?

**Comment by fcakyon** [comment]
yes, thank you!

**Comment by adrien-layer** [comment]
awesome :) thank you for your constructive feedback!

would you benefit from anything else from the active context?

on our roadmap we also have https://github.com/layerai/roadmap/issues/22 , I would be very interested to know your thoughts about that
